# Generated by Django 3.2.8 on 2021-10-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=5000)),
                ('title', models.CharField(max_length=5000)),
                ('author', models.CharField(max_length=5000)),
                ('slug', models.CharField(max_length=5000)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
