# Generated by Django 3.2.8 on 2021-10-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5000)),
                ('phone', models.IntegerField(default=5000)),
                ('email', models.CharField(max_length=500)),
                ('content', models.TextField()),
            ],
        ),
    ]
